steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '--build-arg',
           'IMAGE_TIMEZONE="America/Chicago"',
           '--build-arg',
           'JMETER_VERSION=${_JMETER_VERSION}',
           '--build-arg',
           'SERVER_PORT=${_SERVER_PORT}',
           '-t',
           'gcr.io/${PROJECT_ID}/jmeter-agent:${_JMETER_VERSION}',
           '.']
substitutions:
  _JMETER_VERSION: 5.1.1 # default value
  _SERVER_PORT: 1099 # default value
images: [
  'gcr.io/${PROJECT_ID}/jmeter-agent'
]